"""added nodeid

Revision ID: 9da2fa96b7e1
Revises: da29916875ec
Create Date: 2022-06-01 10:04:18.811887

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9da2fa96b7e1'
down_revision = 'da29916875ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvester_events', sa.Column('nodeid', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harvester_events', 'nodeid')
    # ### end Alembic commands ###
